import { connectToDatabase } from './database';
import { User } from './models';

const newDoctorData = [
  {
    name: 'Sushila Devi Singh',
    phone: '+977 9876543210',
    specialty: 'Cardiologist',
    email: 'sushila.devi.singh@medicateconnect.com',
    password: 'password123',
    role: 'doctor',
    experience: 8,
    license: 'MD123456',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Upendra Devkota',
    phone: '+977 9876543211',
    specialty: 'Dermatologist',
    email: 'upendra.devkota@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 10,
    license: 'MD123457',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Sanjay Rathi',
    phone: '+977 9876543212',
    specialty: 'Pediatrician',
    email: 'sanjay.rathi@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 12,
    license: 'MD123458',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Gyanendra Gurung',
    phone: '+977 9876543213',
    specialty: 'Orthopedic',
    email: 'gyanendra.gurung@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 15,
    license: 'MD123459',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Baikuntha Adhikari',
    phone: '+977 9876543214',
    specialty: 'Neurologist',
    email: 'baikuntha.adhikari@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 9,
    license: 'MD123460',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Ashok Koirala',
    phone: '+977 9876543215',
    specialty: 'Psychiatrist',
    email: 'ashok.koirala@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 11,
    license: 'MD123461',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Rina Sharma',
    phone: '+977 9876543216',
    specialty: 'General Practitioner',
    email: 'rina.sharma@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 7,
    license: 'MD123462',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Bikash Thapa',
    phone: '+977 9876543217',
    specialty: 'Surgeon',
    email: 'bikash.thapa@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 14,
    license: 'MD123463',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Sunita Rai',
    phone: '+977 9876543218',
    specialty: 'Ophthalmologist',
    email: 'sunita.rai@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 6,
    license: 'MD123464',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Rajendra Pandey',
    phone: '+977 9876543219',
    specialty: 'Gynecologist',
    email: 'rajendra.pandey@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 13,
    license: 'MD123465',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Anjali Lama',
    phone: '+977 9876543220',
    specialty: 'Dentist',
    email: 'anjali.lama@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 8,
    license: 'MD123466',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Prakash Bhattarai',
    phone: '+977 9876543221',
    specialty: 'Radiologist',
    email: 'prakash.bhattarai@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 10,
    license: 'MD123467',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Kumari Shrestha',
    phone: '+977 9876543222',
    specialty: 'Endocrinologist',
    email: 'kumari.shrestha@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 9,
    license: 'MD123468',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Dinesh Khadka',
    phone: '+977 9876543223',
    specialty: 'Urologist',
    email: 'dinesh.khadka@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 12,
    license: 'MD123469',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Maya Tamang',
    phone: '+977 9876543224',
    specialty: 'Oncologist',
    email: 'maya.tamang@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 16,
    license: 'MD123470',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Suresh Maharjan',
    phone: '+977 9876543225',
    specialty: 'Pulmonologist',
    email: 'suresh.maharjan@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 11,
    license: 'MD123471',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Poonam Basnet',
    phone: '+977 9876543226',
    specialty: 'Nephrologist',
    email: 'poonam.basnet@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 8,
    license: 'MD123472',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Hari Prasad',
    phone: '+977 9876543227',
    specialty: 'Hematologist',
    email: 'hari.prasad@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 14,
    license: 'MD123473',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Sabina Joshi',
    phone: '+977 9876543228',
    specialty: 'Rheumatologist',
    email: 'sabina.joshi@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 7,
    license: 'MD123474',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Ram Kumar',
    phone: '+977 9876543229',
    specialty: 'Allergist',
    email: 'ram.kumar@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 9,
    license: 'MD123475',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Gita Poudel',
    phone: '+977 9876543230',
    specialty: 'Infectious Disease Specialist',
    email: 'gita.poudel@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 10,
    license: 'MD123476',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Nabin Ghimire',
    phone: '+977 9876543231',
    specialty: 'Emergency Medicine',
    email: 'nabin.ghimire@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 13,
    license: 'MD123477',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Laxmi Bhandari',
    phone: '+977 9876543232',
    specialty: 'Family Medicine',
    email: 'laxmi.bhandari@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 6,
    license: 'MD123478',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Krishna Acharya',
    phone: '+977 9876543233',
    specialty: 'Internal Medicine',
    email: 'krishna.acharya@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 15,
    license: 'MD123479',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Manju Khatri',
    phone: '+977 9876543234',
    specialty: 'Pathologist',
    email: 'manju.khatri@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 11,
    license: 'MD123480',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Dipak Rijal',
    phone: '+977 9876543235',
    specialty: 'Anesthesiologist',
    email: 'dipak.rijal@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 12,
    license: 'MD123481',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Sarita Dahal',
    phone: '+977 9876543236',
    specialty: 'Sports Medicine',
    email: 'sarita.dahal@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 8,
    license: 'MD123482',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Bishnu Paudel',
    phone: '+977 9876543237',
    specialty: 'Plastic Surgeon',
    email: 'bishnu.paudel@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 14,
    license: 'MD123483',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Rekha Thakuri',
    phone: '+977 9876543238',
    specialty: 'Obstetrician',
    email: 'rekha.thakuri@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 9,
    license: 'MD123484',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Santosh Adhikari',
    phone: '+977 9876543239',
    specialty: 'Cardiothoracic Surgeon',
    email: 'santosh.adhikari@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 17,
    license: 'MD123485',
    rating: 5,
    isAvailable: true,
  },
  {
    name: 'Nisha Gurung',
    phone: '+977 9876543240',
    specialty: 'Vascular Surgeon',
    email: 'nisha.gurung@medicateconnect.com',
    password: '12345',
    role: 'doctor',
    experience: 10,
    license: 'MD123486',
    rating: 5,
    isAvailable: true,
  },
];

async function seedDoctors() {
  try {
    await connectToDatabase();

    console.log('Clearing existing doctors...');
    await User.deleteMany({ role: 'doctor' });

    console.log('Seeding doctors...');

    for (const doctorData of newDoctorData) {
      // Assign random rating between 3 and 5
      const randomRating = Math.floor(Math.random() * 3) + 3; // 3, 4, or 5
      const doctorWithRating = { ...doctorData, rating: randomRating };

      const newDoctor = new User(doctorWithRating);
      await newDoctor.save();
      console.log(`Created doctor: ${doctorData.name} with rating ${randomRating}`);
    }

    console.log('All doctors seeded successfully');
  } catch (error) {
    console.error('Error seeding doctors:', error);
  } finally {
    process.exit(0);
  }
}

seedDoctors();
